-- Migration 009: Add DocNomads Plus and film study-abroad scholarships
-- Uses INSERT OR IGNORE — safe to re-run

INSERT OR IGNORE INTO education_residency
  (name, name_vi, organization, country, city, website, type, duration, deadline,
   stipend, covers_travel, covers_accommodation, eligibility, eligibility_vi, description, description_vi, status)
VALUES

-- ── DocNomads Plus ────────────────────────────────────────────────────────────
('DocNomads+ Joint MA in Documentary Film',
 'DocNomads+ Thạc sĩ Liên kết Phim Tài liệu',
 'DocNomads Consortium (Lisbon / Brussels / Budapest)',
 'Portugal', 'Lisbon',
 'https://docnomads.eu',
 'scholarship', '2 years', '2026-02-15',
 10800, 1, 1,
 'Bachelor degree graduates; all nationalities. Funded by Erasmus Mundus.',
 'Nhà làm phim tốt nghiệp đại học; mọi quốc tịch. Được tài trợ Erasmus Mundus.',
 'Erasmus Mundus Joint Master Degree in documentary film directing (2 years), rotating between Lisbon, Brussels and Budapest. Full scholarship covers tuition, monthly allowance €1,000–€1,440, travel grants and installation cost.',
 'Thạc sĩ liên kết Erasmus Mundus về đạo diễn phim tài liệu (2 năm), luân phiên giữa Lisbon, Brussels và Budapest. Học bổng toàn phần bao gồm học phí, phụ cấp hàng tháng €1.000–€1.440, tài trợ đi lại và chi phí định cư.',
 'active'),

-- ── CSC — Italy National Film School ─────────────────────────────────────────
('CSC — Centro Sperimentale di Cinematografia',
 'CSC — Trường Phim Quốc gia Italia',
 'Centro Sperimentale di Cinematografia / MIC',
 'Italy', 'Rome',
 'https://www.fondazionecsc.it',
 'scholarship', '3 years', '2026-04-30',
 0, 0, 0,
 'Open to international students (non-EU). Competitive selection. Italian required for some courses.',
 'Mở cho sinh viên quốc tế. Tuyển sinh cạnh tranh. Một số ngành yêu cầu tiếng Ý.',
 'Italy''s national film school (founded 1935). Free tuition for international students. Specialisations: directing, screenwriting, cinematography, documentary, VFX and more.',
 'Trường phim quốc gia Italia (thành lập 1935). Miễn học phí cho sinh viên quốc tế. Các chuyên ngành: đạo diễn, biên kịch, quay phim, phim tài liệu, VFX và nhiều hơn nữa.',
 'active'),

-- ── FAMU International — Czech Republic ──────────────────────────────────────
('FAMU International — Film and TV School Prague',
 'FAMU International — Trường Phim & Truyền hình Prague',
 'FAMU — Film and TV School of the Academy of Performing Arts',
 'Czech Republic', 'Prague',
 'https://www.famu.cz/en/',
 'scholarship', '1-3 years', '2026-03-15',
 0, 0, 0,
 'Bachelor and Master applicants worldwide. English-taught programmes. Czech Government Scholarship available.',
 'Ứng viên đại học và thạc sĩ toàn cầu. Chương trình dạy bằng tiếng Anh. Học bổng Chính phủ Séc có sẵn.',
 'One of Europe''s oldest and most prestigious film schools (est. 1946). English-taught MFA programmes. Czech Government Scholarships (via DZS) available for developing-country applicants.',
 'Một trong những trường phim lâu đời và uy tín nhất châu Âu (thành lập 1946). Chương trình MFA dạy bằng tiếng Anh. Học bổng Chính phủ Séc (qua DZS) dành cho ứng viên từ các nước đang phát triển.',
 'active'),

-- ── DAAD — German Film School Scholarships ────────────────────────────────────
('DAAD Scholarship for German Film Schools (HFF / DFFB / ifs)',
 'Học bổng DAAD cho các Trường Phim Đức',
 'DAAD — Deutscher Akademischer Austauschdienst',
 'Germany', 'Munich / Berlin / Cologne',
 'https://www.daad.de/en/study-and-research-in-germany/scholarships/',
 'scholarship', '1-2 years', '2026-11-15',
 1200, 1, 0,
 'International graduates; strong portfolio required. Applies to HFF München, DFFB Berlin, ifs Cologne.',
 'Tốt nghiệp quốc tế; cần portfolio mạnh. Áp dụng cho HFF München, DFFB Berlin, ifs Cologne.',
 'DAAD study scholarships for international postgraduate students admitted to German film schools (HFF München, DFFB, ifs Cologne). Monthly stipend ~€1,200 + travel allowance.',
 'Học bổng DAAD cho sinh viên sau đại học quốc tế được nhận vào các trường phim Đức (HFF München, DFFB, ifs Cologne). Phụ cấp hàng tháng ~€1.200 + trợ cấp đi lại.',
 'active'),

-- ── Holland Scholarship — Dutch Film Schools ──────────────────────────────────
('Holland Scholarship — Dutch Film & Art Schools (NFTA / NFI)',
 'Học bổng Holland — Trường Phim & Nghệ thuật Hà Lan',
 'Nuffic / Dutch Ministry of Education',
 'Netherlands', 'Amsterdam / Utrecht',
 'https://www.studyinholland.nl/scholarships/find-a-scholarship/holland-scholarship',
 'scholarship', '1 year', '2026-02-01',
 5000, 0, 0,
 'Non-EU/EEA students applying to Dutch higher education (NFTA, NFI, HKU, ArtEZ). Bachelor or Master.',
 'Sinh viên ngoài EU/EEA đăng ký học tại các trường đại học Hà Lan (NFTA, NFI, HKU, ArtEZ). Đại học hoặc Thạc sĩ.',
 'One-time grant of €5,000 for non-EU students enrolling in a Dutch film or art school. Covers schools such as Netherlands Film Academy (NFTA) and Netherlands Film Institute (NVI).',
 'Tài trợ một lần €5.000 cho sinh viên ngoài EU đăng ký học tại trường phim hoặc nghệ thuật Hà Lan. Bao gồm các trường như Học viện Phim Hà Lan (NFTA) và Viện Phim Hà Lan (NVI).',
 'active'),

-- ── Locarno Film Academy ──────────────────────────────────────────────────────
('Locarno Film Academy',
 'Học viện Phim Locarno',
 'Locarno Film Festival',
 'Switzerland', 'Locarno',
 'https://www.locarnofestival.ch/LFF/academy.html',
 'scholarship', '10 days', '2026-04-30',
 0, 1, 1,
 'Emerging filmmakers and film critics under 30. Fully funded (travel + accommodation + festival accreditation).',
 'Nhà làm phim và nhà phê bình phim mới nổi dưới 30 tuổi. Toàn phần (đi lại + chỗ ở + thẻ LHP).',
 'Intensive 10-day fee-waived academy at Locarno Film Festival. Masterclasses, screenings, and networking with international industry. Fully funded — travel, accommodation and festival accreditation included.',
 'Học viện 10 ngày miễn phí tại Liên hoan phim Locarno. Masterclass, chiếu phim và kết nối với ngành quốc tế. Toàn phần — bao gồm đi lại, chỗ ở và thẻ LHP.',
 'active'),

-- ── Cannes Cinéfondation Atelier ──────────────────────────────────────────────
('Cannes Cinéfondation Atelier',
 'Atelier Cinéfondation Cannes',
 'Festival de Cannes — Cinéfondation',
 'France', 'Cannes',
 'https://cinemadedemain.festival-cannes.com/en/supporting/the-atelier/',
 'scholarship', '1 week', '2026-01-15',
 0, 1, 1,
 'Filmmakers with a second or third feature in development. Selected by invitation / submission.',
 'Nhà làm phim đang phát triển phim dài thứ hai hoặc thứ ba. Được chọn theo lời mời / nộp hồ sơ.',
 'Biennial residency program at the Cannes Film Festival. Offers 15 emerging directors a week of industry meetings, co-production talks and networking. Fully funded (travel + accommodation).',
 'Chương trình lưu trú tại Liên hoan phim Cannes hai năm một lần. Cung cấp cho 15 đạo diễn mới nổi một tuần gặp gỡ ngành, đàm phán đồng sản xuất và kết nối. Toàn phần (đi lại + chỗ ở).',
 'active'),

-- ── Norwegian Film School ─────────────────────────────────────────────────────
('Norwegian Film School — MFA Film Directing',
 'Trường Phim Na Uy — MFA Đạo diễn',
 'Inland Norway University of Applied Sciences (INN)',
 'Norway', 'Lillehammer',
 'https://www.filmschool.no/en/',
 'scholarship', '2 years', '2026-03-01',
 0, 0, 0,
 'International students. EEA students: free tuition. Non-EEA: tuition fees apply. Strong portfolio required.',
 'Sinh viên quốc tế. Sinh viên EEA: miễn học phí. Ngoài EEA: có học phí. Cần portfolio mạnh.',
 'Two-year MFA in Film Directing. EEA students pay no tuition. Fully English-taught. Ranked among Europe''s best. Norwegian Government Quota Scholarships available for select non-EU countries.',
 'MFA 2 năm về Đạo diễn Phim. Sinh viên EEA không mất học phí. Dạy hoàn toàn bằng tiếng Anh. Xếp hạng trong số các trường tốt nhất châu Âu. Học bổng Quota Chính phủ Na Uy dành cho một số nước ngoài EU.',
 'active'),

-- ── Den Danske Filmskole ──────────────────────────────────────────────────────
('National Film School of Denmark',
 'Trường Phim Quốc gia Đan Mạch',
 'Den Danske Filmskole',
 'Denmark', 'Copenhagen',
 'https://www.filmskolen.dk/english/',
 'scholarship', '4 years', '2026-02-01',
 0, 0, 0,
 'International applicants welcome. Competitive selection. Danish Government Scholarships (DHGU) available.',
 'Chào đón ứng viên quốc tế. Tuyển sinh cạnh tranh. Học bổng Chính phủ Đan Mạch (DHGU) có sẵn.',
 'Denmark''s prestigious national film school. 4-year professional programmes in directing, cinematography, editing, sound and production design. State-funded — no tuition for accepted students. Danish Government DHGU scholarships available for non-EU applicants.',
 'Trường phim quốc gia uy tín của Đan Mạch. Chương trình chuyên nghiệp 4 năm về đạo diễn, quay phim, dựng phim, âm thanh và thiết kế sản xuất. Được nhà nước tài trợ — miễn học phí cho sinh viên được nhận. Học bổng DHGU Chính phủ Đan Mạch dành cho ứng viên ngoài EU.',
 'active'),

-- ── Produire au Sud (PaS) ─────────────────────────────────────────────────────
('Produire au Sud (PaS) — Nantes',
 'Produire au Sud (PaS) — Nantes',
 '3 Continents Festival',
 'France', 'Nantes',
 'https://www.3continents.com/en/produire-au-sud/',
 'scholarship', '1 week', '2026-06-30',
 0, 1, 1,
 'Producer–director teams from Africa, Asia, Latin America and Middle East. Projects in development.',
 'Đội ngũ nhà sản xuất – đạo diễn từ châu Phi, châu Á, Mỹ Latinh và Trung Đông. Các dự án đang phát triển.',
 'International coproduction workshop for filmmakers from the global South. Fully funded residency in Nantes; connects producers with European partners, financiers and distributors.',
 'Workshop đồng sản xuất quốc tế cho nhà làm phim từ các nước đang phát triển. Lưu trú toàn phần tại Nantes; kết nối nhà sản xuất với đối tác châu Âu, nhà tài chính và nhà phân phối.',
 'active'),

-- ── Tribeca X Stowe Story Labs ────────────────────────────────────────────────
('Stowe Story Labs — Narrative & Documentary Fellowships',
 'Stowe Story Labs — Học bổng Phim Truyện & Tài liệu',
 'Stowe Story Labs',
 'USA', 'Vermont',
 'https://www.stowestorylabs.com',
 'scholarship', '1 week', '2026-05-01',
 0, 1, 1,
 'Emerging screenwriters and documentary filmmakers. US and international. Project must be in development.',
 'Nhà biên kịch và nhà làm phim tài liệu mới nổi. Mỹ và quốc tế. Dự án phải đang trong giai đoạn phát triển.',
 'Intensive week-long fellowship retreats in Vermont for screenwriters and documentary filmmakers. Master workshops with industry mentors. Travel and accommodation fully covered.',
 'Học bổng rút lui một tuần chuyên sâu tại Vermont cho biên kịch và nhà làm phim tài liệu. Workshop nâng cao với cố vấn ngành. Đi lại và chỗ ở được bao trọn.',
 'active');
