-- Migration 013: Festival Insights — AI-generated profile data
-- Generated by Claude Sonnet on first profile view, cached indefinitely
-- Owner can force regenerate via DELETE /api/festivals/:id/insights

CREATE TABLE IF NOT EXISTS festival_insights (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  festival_id INTEGER NOT NULL UNIQUE REFERENCES festivals(id) ON DELETE CASCADE,

  -- Narrative fields (plain text)
  summary TEXT,               -- 2-3 paragraph overview of the festival
  what_they_look_for TEXT,   -- Curatorial taste, thematic focus, aesthetic preferences
  eligibility TEXT,           -- Premiere reqs, nationality, film length/type, language
  industry_presence TEXT,     -- Buyers, distributors, press, markets, networking
  tips TEXT,                  -- Practical advice for applicants

  -- Structured JSON fields
  past_selections TEXT,       -- JSON: PastFilm[]
  prizes TEXT,                -- JSON: FestivalPrize[]
  useful_links TEXT,          -- JSON: UsefulLink[]
  acceptance_stats TEXT,      -- JSON: AcceptanceStat | null

  -- Metadata
  confidence TEXT DEFAULT 'medium',   -- 'high' | 'medium' | 'low'
  generated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  model_used TEXT DEFAULT 'claude-sonnet-4-6'
);

CREATE INDEX IF NOT EXISTS idx_insights_festival ON festival_insights(festival_id);
