-- IFT Seed Data
-- Sample data for development (dates in 2026/2027)

-- Festivals (curated: FIAPF A-list + major international + Asia focus)
-- Uses INSERT OR IGNORE — safe to re-run, won't overwrite existing data
INSERT OR IGNORE INTO festivals (name, name_vi, country, city, website, category, tier, early_deadline, regular_deadline, description, description_vi, source) VALUES
-- FIAPF A-list Competitive
('Cannes Film Festival 2026', 'Liên hoan phim Cannes 2026', 'France', 'Cannes', 'https://festival-cannes.com', 'narrative', 'A-list', '2026-01-15', '2026-02-15', 'The world''s most prestigious film festival. Palme d''Or competition.', 'Liên hoan phim uy tín nhất thế giới. Giải Cành cọ vàng.', 'manual'),
('Berlin International Film Festival 2027', 'Berlinale 2027', 'Germany', 'Berlin', 'https://berlinale.de', 'narrative', 'A-list', '2026-09-15', '2026-10-15', 'One of the world''s leading film festivals. Golden Bear competition.', 'Một trong những LHP hàng đầu thế giới. Giải Gấu vàng.', 'manual'),
('Venice Film Festival 2026', 'Liên hoan phim Venice 2026', 'Italy', 'Venice', 'https://labiennale.org/en/cinema', 'narrative', 'A-list', '2026-04-01', '2026-05-01', 'The world''s oldest film festival. Golden Lion competition.', 'LHP lâu đời nhất thế giới. Giải Sư tử vàng.', 'manual'),
('Locarno Film Festival 2026', 'Liên hoan phim Locarno 2026', 'Switzerland', 'Locarno', 'https://locarnofestival.ch', 'narrative', 'A-list', '2026-03-01', '2026-03-31', 'FIAPF accredited competitive festival. Golden Leopard competition.', 'LHP cạnh tranh được FIAPF công nhận. Giải Báo vàng.', 'manual'),
('San Sebastián International Film Festival 2026', 'LHP Quốc tế San Sebastián 2026', 'Spain', 'San Sebastián', 'https://sansebastianfestival.com', 'narrative', 'A-list', '2026-04-01', '2026-05-01', 'FIAPF accredited competitive festival. Golden Shell competition.', 'LHP cạnh tranh FIAPF. Giải Vỏ sò vàng.', 'manual'),
('Shanghai International Film Festival 2026', 'LHP Quốc tế Thượng Hải 2026', 'China', 'Shanghai', 'https://siff.com', 'narrative', 'A-list', '2026-02-15', '2026-03-15', 'Asia''s premier FIAPF accredited competitive film festival.', 'LHP cạnh tranh FIAPF hàng đầu châu Á.', 'manual'),
('Tokyo International Film Festival 2026', 'LHP Quốc tế Tokyo 2026', 'Japan', 'Tokyo', 'https://tiff-jp.net', 'narrative', 'A-list', '2026-05-31', '2026-06-30', 'Japan''s largest international film festival. FIAPF accredited.', 'LHP quốc tế lớn nhất Nhật Bản. Được FIAPF công nhận.', 'manual'),
('Warsaw Film Festival 2026', 'LHP Warsaw 2026', 'Poland', 'Warsaw', 'https://wff.pl', 'narrative', 'A-list', '2026-05-31', '2026-06-30', 'FIAPF accredited competitive festival in Poland.', 'LHP cạnh tranh FIAPF tại Ba Lan.', 'manual'),
('Tallinn Black Nights Film Festival 2026', 'Black Nights Tallinn 2026', 'Estonia', 'Tallinn', 'https://poff.ee', 'narrative', 'A-list', '2026-06-01', '2026-07-01', 'Northern Europe''s largest film festival. FIAPF accredited.', 'LHP lớn nhất Bắc Âu. Được FIAPF công nhận.', 'manual'),
('Karlovy Vary International Film Festival 2026', 'LHP Quốc tế Karlovy Vary 2026', 'Czech Republic', 'Karlovy Vary', 'https://kviff.com', 'narrative', 'A-list', '2026-02-15', '2026-03-15', 'Central Europe''s most prestigious film festival. FIAPF accredited.', 'LHP uy tín nhất Trung Âu. Được FIAPF công nhận.', 'manual'),
('Cairo International Film Festival 2026', 'LHP Quốc tế Cairo 2026', 'Egypt', 'Cairo', 'https://cairofilmfest.org', 'narrative', 'A-list', '2026-07-31', '2026-08-31', 'Africa and Middle East''s most prominent film festival. FIAPF accredited.', 'LHP nổi bật nhất châu Phi và Trung Đông. FIAPF.', 'manual'),
('Mar del Plata International Film Festival 2026', 'LHP Quốc tế Mar del Plata 2026', 'Argentina', 'Mar del Plata', 'https://mardelplatafilmfest.com', 'narrative', 'A-list', '2026-07-15', '2026-08-15', 'Latin America''s only FIAPF accredited competitive film festival.', 'LHP cạnh tranh FIAPF duy nhất tại Mỹ Latinh.', 'manual'),
-- Major Top-Tier (non-FIAPF but globally recognized)
('Toronto International Film Festival 2026', 'TIFF 2026', 'Canada', 'Toronto', 'https://tiff.net', 'narrative', 'A-list', '2026-04-01', '2026-05-01', 'One of the most influential film festivals in the world. Major industry event.', 'Một trong những LHP có ảnh hưởng nhất thế giới.', 'manual'),
('Sundance Film Festival 2027', 'Liên hoan phim Sundance 2027', 'USA', 'Park City', 'https://sundance.org', 'documentary', 'A-list', '2026-08-15', '2026-09-15', 'Premier festival for independent films. Grand Jury Prize.', 'LHP hàng đầu cho phim độc lập. Giải Đại hội đồng.', 'manual'),
('Tribeca Film Festival 2026', 'LHP Tribeca 2026', 'USA', 'New York', 'https://tribecafilm.com', 'narrative', 'A-list', '2026-01-01', '2026-01-31', 'New York''s major film festival founded by Robert De Niro.', 'LHP lớn của New York, sáng lập bởi Robert De Niro.', 'manual'),
('SXSW Film Festival 2026', 'SXSW 2026', 'USA', 'Austin', 'https://sxsw.com/film', 'narrative', 'A-list', '2025-08-01', '2025-08-31', 'Major US film and music festival. Strong platform for emerging filmmakers.', 'LHP và âm nhạc lớn tại Mỹ. Nền tảng mạnh cho nhà làm phim mới.', 'manual'),
('New York Film Festival 2026', 'LHP New York 2026', 'USA', 'New York', 'https://filmlinc.org', 'narrative', 'A-list', '2026-05-01', '2026-05-31', 'Prestigious curated festival presented by Film at Lincoln Center.', 'LHP uy tín do Film at Lincoln Center tổ chức.', 'manual'),
('Rotterdam International Film Festival 2027', 'IFFR 2027', 'Netherlands', 'Rotterdam', 'https://iffr.com', 'narrative', 'A-list', '2026-09-01', '2026-10-01', 'Platform for innovative and cutting-edge world cinema.', 'Nền tảng cho điện ảnh thế giới sáng tạo và tiên phong.', 'manual'),
('IDFA Amsterdam 2026', 'IDFA Amsterdam 2026', 'Netherlands', 'Amsterdam', 'https://idfa.nl', 'documentary', 'A-list', '2026-06-01', '2026-07-15', 'World''s largest documentary film festival.', 'LHP tài liệu lớn nhất thế giới.', 'manual'),
('Hot Docs 2026', 'Hot Docs 2026', 'Canada', 'Toronto', 'https://hotdocs.ca', 'documentary', 'A-list', '2026-10-01', '2026-11-15', 'North America''s largest documentary festival.', 'LHP tài liệu lớn nhất Bắc Mỹ.', 'manual'),
('CPH:DOX 2027', 'CPH:DOX 2027', 'Denmark', 'Copenhagen', 'https://cphdox.dk', 'documentary', 'A-list', '2026-10-01', '2026-11-01', 'One of the world''s leading documentary film festivals.', 'Một trong những LHP tài liệu hàng đầu thế giới.', 'manual'),
('Visions du Réel 2026', 'Visions du Réel 2026', 'Switzerland', 'Nyon', 'https://visionsdureel.ch', 'documentary', 'A-list', '2025-12-01', '2025-12-31', 'International documentary and fiction film festival in Nyon.', 'LHP tài liệu và hư cấu quốc tế tại Nyon.', 'manual'),
('Sheffield DocFest 2026', 'Sheffield DocFest 2026', 'UK', 'Sheffield', 'https://sheffdocfest.com', 'documentary', 'A-list', '2025-12-01', '2026-01-15', 'UK''s largest documentary festival and market.', 'LHP tài liệu và thị trường lớn nhất Vương quốc Anh.', 'manual'),
('Thessaloniki International Film Festival 2026', 'LHP Quốc tế Thessaloniki 2026', 'Greece', 'Thessaloniki', 'https://filmfestival.gr', 'narrative', 'regional', '2026-06-01', '2026-07-01', 'Greece''s major international film festival. Strong platform for Balkan cinema.', 'LHP quốc tế lớn của Hy Lạp. Nền tảng mạnh cho điện ảnh Balkan.', 'manual'),
('Clermont-Ferrand International Short Film Festival 2027', 'LHP Ngắn Quốc tế Clermont-Ferrand 2027', 'France', 'Clermont-Ferrand', 'https://clermont-filmfest.org', 'short', 'A-list', '2026-09-01', '2026-10-01', 'World''s most important short film festival and market.', 'LHP ngắn và thị trường quan trọng nhất thế giới.', 'manual'),
('Oberhausen International Short Film Festival 2026', 'LHP Ngắn Oberhausen 2026', 'Germany', 'Oberhausen', 'https://kurzfilmtage.de', 'short', 'A-list', '2025-11-01', '2025-11-30', 'One of the world''s oldest and most prestigious short film festivals.', 'Một trong những LHP ngắn lâu đời và uy tín nhất thế giới.', 'manual'),
-- Asia Focus
('Busan International Film Festival 2026', 'LHP Quốc tế Busan 2026', 'South Korea', 'Busan', 'https://biff.kr', 'narrative', 'A-list', '2026-05-01', '2026-06-30', 'Asia''s leading film festival. New Currents competition for Asian filmmakers.', 'LHP hàng đầu châu Á. Hạng mục New Currents cho nhà làm phim châu Á.', 'manual'),
('Hong Kong International Film Festival 2027', 'LHP Quốc tế Hồng Kông 2027', 'Hong Kong', 'Hong Kong', 'https://hkiff.org.hk', 'narrative', 'regional', '2026-09-01', '2026-10-01', 'Asia''s premier showcase for Chinese-language and Asian cinema.', 'Sân khấu hàng đầu châu Á cho điện ảnh tiếng Trung và châu Á.', 'manual'),
('Jeonju International Film Festival 2026', 'LHP Quốc tế Jeonju 2026', 'South Korea', 'Jeonju', 'https://jiff.or.kr', 'narrative', 'regional', '2025-12-15', '2026-01-15', 'Korea''s festival dedicated to independent and alternative cinema.', 'LHP Hàn Quốc dành cho điện ảnh độc lập và thay thế.', 'manual'),
('Singapore International Film Festival 2026', 'LHP Quốc tế Singapore 2026', 'Singapore', 'Singapore', 'https://sgiff.com', 'narrative', 'regional', '2026-07-01', '2026-08-01', 'Southeast Asia''s longest-running international film festival.', 'LHP quốc tế chạy dài lâu nhất Đông Nam Á.', 'manual'),
('Golden Horse Film Festival 2026', 'LHP Kim Mã 2026', 'Taiwan', 'Taipei', 'https://goldenhorse.org.tw', 'narrative', 'regional', '2026-06-01', '2026-07-01', 'The most prestigious Chinese-language film awards in the world.', 'Giải thưởng điện ảnh tiếng Trung uy tín nhất thế giới.', 'manual'),
('Osaka Asian Film Festival 2027', 'LHP châu Á Osaka 2027', 'Japan', 'Osaka', 'https://oaff.jp', 'narrative', 'regional', '2026-09-01', '2026-10-15', 'Festival dedicated to Asian cinema with focus on emerging filmmakers.', 'LHP dành cho điện ảnh châu Á tập trung vào nhà làm phim mới nổi.', 'manual'),
('Taipei Film Festival 2026', 'LHP Đài Bắc 2026', 'Taiwan', 'Taipei', 'https://taipeiff.taipei', 'narrative', 'regional', '2026-01-01', '2026-01-31', 'Annual film festival in Taipei celebrating Asian and international cinema.', 'LHP thường niên tại Đài Bắc tôn vinh điện ảnh châu Á và quốc tế.', 'manual'),
('Jogja-NETPAC Asian Film Festival 2026', 'JAFF 2026', 'Indonesia', 'Yogyakarta', 'https://jaff-filmfest.org', 'narrative', 'regional', '2026-07-01', '2026-08-01', 'Indonesia''s premier festival dedicated to Asian cinema.', 'LHP hàng đầu Indonesia dành cho điện ảnh châu Á.', 'manual');

-- Funds & Grants
INSERT OR IGNORE INTO funds_grants (name, name_vi, organization, country, website, type, focus, region_focus, max_amount, currency, deadline, eligibility, eligibility_vi, description, description_vi) VALUES
('Hubert Bals Fund', 'Quỹ Hubert Bals', 'International Film Festival Rotterdam (IFFR)', 'Netherlands', 'https://iffr.com/en/professionals/hubert-bals-fund', 'development', 'narrative', 'global', 10000, 'EUR', '2026-09-01', 'Filmmakers from Asia, Africa, Latin America, Middle East, and Eastern Europe.', 'Nhà làm phim từ châu Á, châu Phi, Mỹ Latinh, Trung Đông và Đông Âu.', 'Supports script and project development for feature films and creative documentaries from developing countries.', 'Hỗ trợ phát triển kịch bản và dự án phim dài và phim tài liệu sáng tạo từ các nước đang phát triển.'),
('IDFA Bertha Fund', 'Quỹ IDFA Bertha', 'International Documentary Film Festival Amsterdam (IDFA)', 'Netherlands', 'https://www.idfa.nl/en/info/idfa-bertha-fund', 'production', 'documentary', 'global', 40000, 'EUR', '2026-05-01', 'Documentary filmmakers from developing countries.', 'Nhà làm phim tài liệu từ các nước đang phát triển.', 'Supports documentary filmmakers from Africa, Asia, Latin America, Middle East and parts of Europe.', 'Hỗ trợ nhà làm phim tài liệu từ châu Phi, châu Á, Mỹ Latinh, Trung Đông và một số nước châu Âu.'),
('Sundance Documentary Fund', 'Quỹ phim tài liệu Sundance', 'Sundance Institute', 'USA', 'https://www.sundance.org/programs/documentary-fund', 'production', 'documentary', 'global', 30000, 'USD', '2026-06-15', 'Documentary filmmakers with a focus on social justice issues.', 'Nhà làm phim tài liệu tập trung vào các vấn đề công bằng xã hội.', 'Supports global documentary projects that address pressing social, cultural, and political issues.', 'Hỗ trợ các dự án phim tài liệu quốc tế đề cập đến các vấn đề xã hội, văn hóa và chính trị cấp bách.'),
('World Cinema Fund', 'Quỹ Điện ảnh Thế giới', 'Berlinale — Berlin International Film Festival', 'Germany', 'https://www.berlinale.de/en/world-cinema-fund/overview.html', 'development', 'narrative', 'global', 60000, 'EUR', '2026-10-15', 'Feature films from Africa, Latin America, Central/Southeast Asia, Middle East, and Eastern Europe.', 'Phim dài từ châu Phi, Mỹ Latinh, Trung/Đông Nam Á, Trung Đông và Đông Âu.', 'Supports the production and distribution of art-house feature films from underrepresented regions.', 'Hỗ trợ sản xuất và phát hành phim dài nghệ thuật từ các khu vực ít được đại diện.'),
('Asian Cinema Fund', 'Quỹ Điện ảnh châu Á', 'Busan International Film Festival (BIFF)', 'South Korea', 'https://acf.busan.go.kr', 'development', 'narrative', 'asia', 20000, 'USD', '2026-04-30', 'Filmmakers from Asian countries.', 'Nhà làm phim từ các quốc gia châu Á.', 'Script development and post-production support for Asian cinema projects.', 'Hỗ trợ phát triển kịch bản và hậu kỳ cho các dự án điện ảnh châu Á.'),
('SEAFIC Lab', 'SEAFIC Lab', 'Southeast Asian Fiction Film Lab', 'Thailand', 'https://www.seafic.net', 'development', 'narrative', 'southeast-asia', 15000, 'USD', '2026-07-31', 'Filmmakers from ASEAN countries for narrative feature development.', 'Nhà làm phim từ các nước ASEAN phát triển phim truyện dài.', 'Script and project development for Southeast Asian fiction films. Annual lab with mentorship and funding.', 'Phát triển kịch bản và dự án phim truyện Đông Nam Á. Lab hàng năm với cố vấn và tài trợ.'),
('Catapult Film Fund', 'Quỹ Catapult Film', 'Catapult Film Fund', 'USA', 'https://catapultfilmfund.org', 'development', 'documentary', 'global', 25000, 'USD', '2026-08-15', 'Documentary filmmakers in development phase.', 'Nhà làm phim tài liệu trong giai đoạn phát triển.', 'Development funding for documentary films. Provides early-stage funding to help documentarians develop their films.', 'Tài trợ phát triển cho phim tài liệu. Cung cấp kinh phí giai đoạn đầu giúp nhà làm phim phát triển tác phẩm.'),
('Doha Film Institute Development Grant', 'Tài trợ Phát triển Viện phim Doha', 'Doha Film Institute', 'Qatar', 'https://www.dohafilminstitute.com/filmmaking/grants', 'development', 'narrative', 'global', 30000, 'USD', '2026-05-31', 'Arab filmmakers and global co-productions.', 'Nhà làm phim Ả Rập và đồng sản xuất quốc tế.', 'Script development and production funding for Arab and international filmmakers.', 'Tài trợ phát triển kịch bản và sản xuất cho nhà làm phim Ả Rập và quốc tế.'),
('Hot Docs Forum', 'Hot Docs Forum', 'Hot Docs Canadian International Documentary Festival', 'Canada', 'https://hotdocs.ca/programmes/hot-docs-forum', 'production', 'documentary', 'global', NULL, 'USD', '2026-11-15', 'Documentary projects seeking co-production and financing partners.', 'Các dự án phim tài liệu tìm kiếm đối tác đồng sản xuất và tài chính.', 'Pitching forum connecting documentary filmmakers with international broadcasters and distributors.', 'Diễn đàn pitch kết nối nhà làm phim tài liệu với các đài truyền hình và nhà phân phối quốc tế.'),
('Purin Pictures Fund', 'Quỹ Purin Pictures', 'Purin Pictures', 'Thailand', 'https://www.purinpictures.com', 'development', 'narrative', 'southeast-asia', 20000, 'USD', '2026-06-30', 'Southeast Asian narrative filmmakers.', 'Nhà làm phim truyện Đông Nam Á.', 'Development and production support for Southeast Asian cinema with focus on emerging voices.', 'Hỗ trợ phát triển và sản xuất điện ảnh Đông Nam Á tập trung vào các tiếng nói mới nổi.'),
('ITVS Open Call', 'ITVS Open Call', 'Independent Television Service (ITVS)', 'USA', 'https://itvs.org/funding/open-call', 'production', 'documentary', 'global', 200000, 'USD', '2026-09-30', 'Independent documentary filmmakers for PBS broadcast.', 'Nhà làm phim tài liệu độc lập cho đài PBS.', 'Funds independent documentary films for broadcast on PBS, with focus on diverse voices and underrepresented communities.', 'Tài trợ phim tài liệu độc lập phát sóng trên PBS, tập trung vào tiếng nói đa dạng và cộng đồng ít được đại diện.'),
('CNC Aide aux cinémas du monde', 'CNC Aide aux cinémas du monde', 'Centre national du cinéma et de limage animée (CNC)', 'France', 'https://www.cnc.fr/professionnels/aides-et-financements/international/aide-aux-cinemas-du-monde', 'production', 'narrative', 'global', 80000, 'EUR', '2026-09-15', 'French-international co-productions with directors from non-EU countries.', 'Đồng sản xuất Pháp-quốc tế với đạo diễn từ các nước ngoài EU.', 'French co-production fund supporting international films directed by filmmakers from non-EU countries.', 'Quỹ đồng sản xuất Pháp hỗ trợ phim quốc tế do đạo diễn từ các nước ngoài EU thực hiện.'),
('Chicken & Egg Pictures Fund', 'Quỹ Chicken & Egg Pictures', 'Chicken & Egg Pictures', 'USA', 'https://chickeneggpics.org', 'production', 'documentary', 'global', 50000, 'USD', '2026-07-01', 'Women-identifying and non-binary documentary filmmakers.', 'Nhà làm phim tài liệu nhận dạng là phụ nữ và phi nhị phân.', 'Supports women-identifying and non-binary nonfiction filmmakers who are underrepresented and under-resourced.', 'Hỗ trợ nhà làm phim phi hư cấu nhận dạng là phụ nữ và phi nhị phân ít được đại diện và thiếu nguồn lực.'),
('Cinemart Co-Production Market', 'Cinemart Thị trường Đồng sản xuất', 'International Film Festival Rotterdam (IFFR)', 'Netherlands', 'https://iffr.com/en/professionals/cinemart', 'development', 'narrative', 'global', NULL, 'EUR', '2026-08-01', 'Feature film projects seeking co-production and financing.', 'Dự án phim dài tìm kiếm đồng sản xuất và tài chính.', 'International co-production and finance market for independent feature films at IFFR Rotterdam.', 'Thị trường đồng sản xuất và tài chính quốc tế cho phim dài độc lập tại IFFR Rotterdam.'),
('Tribeca Film Institute Documentary Fund', 'Quỹ phim tài liệu Tribeca Film Institute', 'Tribeca Film Institute', 'USA', 'https://www.tribecafilminstitute.org', 'production', 'documentary', 'global', 25000, 'USD', '2026-05-15', 'Documentary filmmakers working on social-issue films.', 'Nhà làm phim tài liệu làm phim về vấn đề xã hội.', 'Supports documentary films that illuminate contemporary social issues and amplify underrepresented voices.', 'Hỗ trợ phim tài liệu phản ánh các vấn đề xã hội đương đại và khuếch đại những tiếng nói ít được đại diện.');

-- Education & Residencies
INSERT OR IGNORE INTO education_residency (name, name_vi, organization, country, city, website, type, duration, deadline, description, description_vi) VALUES
('Berlinale Talents 2027', 'Berlinale Talents 2027', 'Berlin International Film Festival', 'Germany', 'Berlin', 'https://berlinale-talents.de', 'lab', '1 week', '2026-10-15', 'International talent development program at the Berlin Film Festival.', 'Chương trình phát triển tài năng quốc tế tại Liên hoan phim Berlin.'),
('Cannes Cinéfondation Residency 2026', 'Khu lưu trú Cinéfondation Cannes 2026', 'Festival de Cannes', 'France', 'Paris', 'https://cinefondation.com', 'residency', '5 months', '2026-03-31', '5-month residency in Paris for filmmakers developing their first or second feature.', 'Khu lưu trú 5 tháng tại Paris cho các nhà làm phim đang phát triển bộ phim dài đầu tiên hoặc thứ hai.'),
('Busan Asian Film School 2026', 'Trường phim châu Á Busan 2026', 'Asian Film Academy', 'South Korea', 'Busan', 'https://asianfilmacademy.kr', 'workshop', '2 weeks', '2026-05-31', 'Intensive filmmaking program during BIFF.', 'Chương trình làm phim chuyên sâu trong BIFF.');
